name: Report per Repository

on: workflow_dispatch

jobs:
  ort:
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: GenomicDataInfrastructure/starter-kit-storage-and-interfaces
            sw-name: starter-kit-storage-and-interfaces
          - repository: GenomicDataInfrastructure/gdi-userportal-ckanext-gdi-userportal
            sw-name: gdi-userportal-ckanext-gdi-userportal
          - repository: GenomicDataInfrastructure/gdi-userportal-frontend
            sw-name: gdi-userportal-frontend
          - repository: GenomicDataInfrastructure/gdi-userportal-apigateway
            sw-name: gdi-userportal-apigateway
          - repository: GenomicDataInfrastructure/gdi-userportal-ckan-docker
            sw-name: gdi-userportal-ckan-docker
          - repository: GenomicDataInfrastructure/gdi-userportal-ckanext-dcat
            sw-name: gdi-userportal-ckanext-dcat
          - repository: GenomicDataInfrastructure/gdi-userportal-ckanext-harvest
            sw-name: gdi-userportal-ckanext-harvest
          - repository: GenomicDataInfrastructure/gdi-userportal-ckanext-scheming
            sw-name: gdi-userportal-ckanext-scheming
          - repository: GenomicDataInfrastructure/gdi-userportal-docs
            sw-name: gdi-userportal-docs
          - repository: GenomicDataInfrastructure/starter-kit-beacon2-ri-api
            sw-name: starter-kit-beacon2-ri-api
          - repository: EGA-archive/beacon2-ri-api
            sw-name: beacon2-ri-api
          - repository: GenomicDataInfrastructure/starter-kit-rems
            sw-name: starter-kit-rems
          - repository: CSCfi/rems
            sw-name: rems
          - repository: GenomicDataInfrastructure/starter-kit-htsget
            sw-name: starter-kit-htsget
          - repository: GenomicDataInfrastructure/starter-kit-containerized-computation
            sw-name: starter-kit-containerized-computation
          - repository: GenomicDataInfrastructure/starter-kit-lsaai-mock
            sw-name: starter-kit-lsaai-mock
          - repository: GenomicDataInfrastructure/starter-kit-lsaai-mock
            sw-name: starter-kit-lsaai-mock
          - repository: GenomicDataInfrastructure/starter-kit-lsaai
            sw-name: starter-kit-lsaai
          - repository: neicnordic/sensitive-data-archive
            sw-name: neicnordic/sensitive-data-archive
          - repository: NBISweden/sda-cli
            sw-name: sda-cli
          - repository: elixir-europe/beacon-network-backend
            sw-name: beacon-network-backend
          - repository: elixir-europe/beacon-network-ui
            sw-name: beacon-network-ui
            
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}
      - uses: oss-review-toolkit/ort-ci-github-action@b6d71a83acba8619f16b30c008f212a7a572f8e8 #v1
        with:
          report-formats: CycloneDx,WebApp,PlainTextTemplate,Opossum
          sw-name: ${{ matrix.sw-name }}
          run: 'cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results'
